# Site settings
title: Zunairah Shahzad
email: zunairahshahzad05@gmail.com
url: zunairahshahzad.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "Zunairah, Website"
skills: "Passionate - Hardworking - Innovative - Curious - Meticulous"
meta_author: Shahzad Zunairah

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d9c375 #80B3FF
  primary-rgb: "179,179,74" #"128,179,255"
  secondary: 01070d #FD6E8A
  secondary-dark: 242526 #A2122F

# Footer settings
footer:
  copyright: Zunairah Shahzad
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/zunairah05/
  - title: stack-overflow
    url: http://replit.com/@ZunairahShahzad
  - title: bitbucket
    url: https://gmail.com/zunairahshahzad05@gmail.com 
  - title: github
    url: http://github.com/zunairahshahzad
  
# Postal address (add as many lines as necessary)
address:
  - line: Preston High School
  - line: 550 Rose St, Cambridge 


# Credits content
credits: 'Through Github I was able to experiment and learn the basic methods of coding a website through their fork option. My passion for learning, curiosity and overall personal enjoyment for learning new frameworks encouraged me to apply the concepts I learned through forking respiratories to create this website.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
